Repository stolostron/magic-mirror, pull requests merged in 2022-06, with the labels that each got.

#2 Add a function to apply Git patches to a remote branch
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/git.test.ts
  src/git.ts
Labels: lgtm, approved, do-not-merge/hold

#4 Make db.ts more concise use async function features
  src/db.ts
Labels: lgtm, approved, do-not-merge/hold

#6 Add the GitHub webhook receiver
  .gitleaks.toml
  README.md
  package-lock.json
  package.json
  src/config.test.ts
  src/config.ts
  src/db.test.ts
  src/db.ts
  src/fixtures/check_suite.completed.json
  src/fixtures/issues.closed.json
  src/fixtures/mock-cert.pem
  src/fixtures/pull_request.closed.json
  src/git.test.ts
  src/git.ts
  src/github.test.ts
  src/github.ts
  src/log.ts
  src/scripts/start-syncer.ts
  src/scripts/start-web.ts
  src/syncer.test.ts
  src/syncer.ts
  src/web.test.ts
  src/web.ts
  tsconfig.json
Labels: lgtm, approved, do-not-merge/hold

#7 Add the Kubernetes deployment configuration
  .dockerignore
  Dockerfile
  README.md
  helm/.helmignore
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/pvc.yaml
  helm/templates/service.yaml
  helm/values.yaml
  images/architecture.png
  package-lock.json
  package.json
  src/db.ts
  src/syncer.ts
  src/web.test.ts
  src/web.ts
Labels: lgtm, approved

#10 Run as non-root user by default
  Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#9 File a GitHub issue when the PR can't be merged
  src/web.test.ts
  src/web.ts
Labels: lgtm, approved

#11 Set the pod security context for write access to the database volume
  helm/values.yaml
Labels: lgtm, approved, dco-signoff: yes

#12 Add Publish GitHub Workflow
  .github/workflows/publish.yml
Labels: lgtm, approved, dco-signoff: yes

#13 Use literal strings where contexts are not available
  .github/workflows/publish.yml
Labels: lgtm, approved, dco-signoff: yes

#15 Use git cherry-pick instead of patch files
  src/git.test.ts
  src/git.ts
  src/syncer.test.ts
  src/syncer.ts
Labels: lgtm, approved, dco-signoff: yes

#16 Consider all PR check runs and commit statuses before merging
  README.md
  package-lock.json
  package.json
  src/fixtures/check_run.completed.json
  src/fixtures/status.json
  src/github.ts
  src/syncer.test.ts
  src/syncer.ts
  src/web.test.ts
  src/web.ts
Labels: lgtm, approved, dco-signoff: yes
